server:
  port: 8443
  ssl:
    key-store: config/keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat
    protocol: TLSv1.2

  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript,text/html
    min-response-size: 2048
